name: flutter_spinbox
description: >-
  SpinBox is a numeric input widget with an input field for entering a specific value,
  and spin buttons for quick, convenient, and accurate value adjustments.
version: 0.13.1
homepage: https://github.com/jpnurmi/flutter_spinbox
repository: https://github.com/jpnurmi/flutter_spinbox
issue_tracker: https://github.com/jpnurmi/flutter_spinbox/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
